"""Build the standalone HTML primer with every figure embedded as a data URI.

Reads out/writeup/PRIMER_voxel_operators.md, converts it, inserts the figures
generated by primer_figures.py at anchored positions, and wraps the result in a
self-contained page. No external requests: the artifact CSP blocks them, so the
images are base64 and the type is a system stack.
"""
import base64
import os
import re
import sys

import markdown

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(ROOT, "out", "writeup", "PRIMER_voxel_operators.md")
FIGS = os.path.join(ROOT, "out", "writeup", "figs_primer")
DST = os.path.join(ROOT, "out", "writeup", "primer.html")

# figure -> (anchor text it follows, caption, wide?)
PLACEMENTS = [
    ("fig1_series.png",
     "with all three phases percolating.",
     "Three real anodes from the coarseness series, one slice each, at the "
     "same physical scale. Everything in this document is measured on these "
     "volumes.", True),
    ("fig2_tpb.png",
     "descriptor of an SOFC anode, because it is proportional to the number of "
     "available reaction sites.",
     "The triple-phase boundary is not a region, it is a curve. A 2D slice "
     "cuts that curve in points; the red marks are nickel voxels touching both "
     "zirconia and pore.", True),
    ("fig4_signature.png",
     "Instead they are anticorrelated across the series.",
     "The measured signature — and the reason only two of its six orderings "
     "can be relied on.", True),
    ("fig3_percolation.png",
     "0.9157 for coarse.",
     "Isolated nickel in the pristine coarse anode. An operator that deletes "
     "this material rewrites the denominator of the metric used to judge it.",
     False),
    ("fig5_swap.png",
     "That is precisely curvature-driven surface diffusion, which is the "
     "physics we wanted.",
     "One real swap, both voxels taken out of the fine tomogram.", True),
    ("fig7_money.png",
     "Read the second column, then the fourth.",
     "The whole argument in one panel. Both curves are divided by their "
     "pristine value so they can share a single axis.", True),
    ("fig6_plateau.png",
     "Roughly four out of five accepted moves **cost nothing** under the "
     "criterion.",
     "Every accepted move on the fine anode, by its cost. The red bar is the "
     "null space of the criterion.", False),
    ("fig8_before_after.png",
     "41 % of them single isolated voxels.",
     "The busiest window in the volume. Most of the nickel that leaves is "
     "taken from against the ceramic.", True),
    ("fig11_counterfactual.png",
     "shifts TPB by four percent.",
     "Re-applying the two groups of moves separately. The contact-adjacent "
     "moves are the entire effect.", False),
    ("fig9_strict.png",
     "not vanish, and it is not close to 1.0.",
     "Forbidding the unpriced moves removes most of the artifact, and not all "
     "of it.", False),
    ("fig10_athermal.png",
     "| 29.1 nm | 1.70 × 10⁻¹⁵ J | 9.9 × 10⁻⁶ | 0.000 |",
     "Why the thermostat cannot help. The dashed line is where thermal "
     "fluctuation could act; the data sits four to five decades above it.",
     False),
]

# display equations, hand-set (no MathJax: the CSP blocks CDNs)
EQ = {
    r"P_{\text{span}} = \frac{\text{Ni voxels in the spanning cluster}}{\text{Ni voxels present now}}":
        "P<sub>span</sub> &nbsp;=&nbsp; <span class='frac'><span>Ni voxels in the spanning cluster</span>"
        "<span>Ni voxels present <em>now</em></span></span>",
    r"\boxed{R_{\text{Ni}}(n) = \frac{\text{Ni voxels in the spanning cluster after } n \text{ rounds}}{\text{Ni voxels in the } \textbf{pristine} \text{ structure}}}":
        "R<sub>Ni</sub>(n) &nbsp;=&nbsp; <span class='frac'><span>Ni voxels in the spanning cluster after n rounds</span>"
        "<span>Ni voxels in the <strong>pristine</strong> structure</span></span>",
    r"\Delta A_{\text{remove}}(a) = n_N(a) - \bigl(6 - n_N(a)\bigr) = 2n_N(a) - 6":
        "ΔA<sub>remove</sub>(a) = n<sub>N</sub>(a) − (6 − n<sub>N</sub>(a)) = 2n<sub>N</sub>(a) − 6",
    r"\Delta A_{\text{add}}(b) = \bigl(6 - n_N(b)\bigr) - n_N(b) = 6 - 2n_N(b)":
        "ΔA<sub>add</sub>(b) = (6 − n<sub>N</sub>(b)) − n<sub>N</sub>(b) = 6 − 2n<sub>N</sub>(b)",
    r"\boxed{\Delta A = 2\bigl[n_N(a) - n_N(b)\bigr]}":
        "<strong>ΔA = 2 [ n<sub>N</sub>(a) − n<sub>N</sub>(b) ]</strong>",
    r"\Delta A \leq 0 \iff n_N(a) \leq n_N(b)":
        "ΔA ≤ 0 &nbsp;⟺&nbsp; n<sub>N</sub>(a) ≤ n<sub>N</sub>(b)",
    r"E = \sum_{\langle ij \rangle} J(\sigma_i, \sigma_j), \qquad \sigma \in \{\text{Ni}, \text{YSZ}, \text{pore}\}":
        "E = Σ<sub>⟨ij⟩</sub> J(σ<sub>i</sub>, σ<sub>j</sub>) &nbsp;&nbsp;&nbsp; "
        "σ ∈ { Ni, YSZ, pore }",
    r"\Delta E = 2 J_{NP}\bigl[n_N(a) - n_N(b)\bigr] + \bigl[n_Y(a) - n_Y(b)\bigr]\bigl(J_{NP} + J_{YP} - J_{NY}\bigr)":
        "ΔE = 2 J<sub>NP</sub> [n<sub>N</sub>(a) − n<sub>N</sub>(b)] "
        "+ [n<sub>Y</sub>(a) − n<sub>Y</sub>(b)] (J<sub>NP</sub> + J<sub>YP</sub> − J<sub>NY</sub>)",
    r"\cos\theta = \frac{J_{YP} - J_{NY}}{J_{NP}}":
        "cos θ &nbsp;=&nbsp; <span class='frac'><span>J<sub>YP</sub> − J<sub>NY</sub></span>"
        "<span>J<sub>NP</sub></span></span>",
    r"\boxed{\Delta E = J_{NP}\Bigl[\,2\bigl(n_N(a) - n_N(b)\bigr) + (1 + \cos\theta)\bigl(n_Y(a) - n_Y(b)\bigr)\Bigr]}":
        "<strong>ΔE = J<sub>NP</sub> [ 2( n<sub>N</sub>(a) − n<sub>N</sub>(b) ) "
        "+ (1 + cos θ)( n<sub>Y</sub>(a) − n<sub>Y</sub>(b) ) ]</strong>",
    r"J_{NP} = \gamma_{\text{Ni}} \times a^2":
        "J<sub>NP</sub> = γ<sub>Ni</sub> × a²",
    r"J_{NP} = 2.0 \times (20 \times 10^{-9})^2 = 8.0 \times 10^{-16}\ \text{J}":
        "J<sub>NP</sub> = 2.0 × (20 × 10⁻⁹)² = 8.0 × 10⁻¹⁶ J",
    r"k_B T = 1.381 \times 10^{-23} \times 1223 = 1.69 \times 10^{-20}\ \text{J}":
        "k<sub>B</sub>T = 1.381 × 10⁻²³ × 1223 = 1.69 × 10⁻²⁰ J",
    r"\frac{J_{NP}}{k_B T} = \frac{8.0 \times 10^{-16}}{1.69 \times 10^{-20}} \approx 4.7 \times 10^{4}":
        "J<sub>NP</sub> / k<sub>B</sub>T &nbsp;=&nbsp; 8.0 × 10⁻¹⁶ / 1.69 × 10⁻²⁰ "
        "&nbsp;≈&nbsp; <strong>4.7 × 10⁴</strong>",
    r"P = \exp\left(-0.357 \times 4.7\times10^4\right) = \exp(-1.7 \times 10^4) \approx 10^{-7300}":
        "P = exp( −0.357 × 4.7 × 10⁴ ) = exp( −1.7 × 10⁴ ) ≈ 10<sup>−7300</sup>",
}

INLINE = [
    (r"\$n_N\(([abx])\)\$", r"<var>n<sub>N</sub>(\1)</var>"),
    (r"\$n_Y\(([abx])\)\$", r"<var>n<sub>Y</sub>(\1)</var>"),
    (r"\$n_P\(([abx])\)\$", r"<var>n<sub>P</sub>(\1)</var>"),
    (r"\$\\Delta A > 0\$", "<var>ΔA &gt; 0</var>"),
    (r"\$\\Delta A < 0\$", "<var>ΔA &lt; 0</var>"),
    (r"\$\\Delta A \\leq 0\$", "<var>ΔA ≤ 0</var>"),
    (r"\$\\Delta A = 0\$", "<var>ΔA = 0</var>"),
    (r"\$\\Delta A\$", "<var>ΔA</var>"),
    (r"\$\\Delta E\$", "<var>ΔE</var>"),
    (r"\$\\gamma_\{\\text\{Ni\}\}\$", "<var>γ<sub>Ni</sub></var>"),
    (r"\$\\gamma_\{\\text\{Ni-YSZ\}\}\$", "<var>γ<sub>Ni-YSZ</sub></var>"),
    (r"\$\\gamma_\{\\text\{YSZ\}\}\$", "<var>γ<sub>YSZ</sub></var>"),
    (r"\$J_\{NP\}\$", "<var>J<sub>NP</sub></var>"),
    (r"\$k_BT\$", "<var>k<sub>B</sub>T</var>"),
    (r"\$kT/J_\{NP\}\$", "<var>kT/J<sub>NP</sub></var>"),
    (r"\$P_\{\\text\{span\}\}\$", "<var>P<sub>span</sub></var>"),
    (r"\$R_\{\\text\{Ni\}\}\$", "<var>R<sub>Ni</sub></var>"),
    (r"\$n_N\$", "<var>n<sub>N</sub></var>"),
    (r"\$n_Y\$", "<var>n<sub>Y</sub></var>"),
    (r"\$A\$", "<var>A</var>"),
    (r"\$a\$", "<var>a</var>"),
    (r"\$b\$", "<var>b</var>"),
    (r"\$\\theta\$", "<var>θ</var>"),
    (r"\$\\cos\\theta = -1\$", "<var>cos θ = −1</var>"),
    (r"\$\\cos\\theta = \+1\$", "<var>cos θ = +1</var>"),
    (r"\$S_\{\\text\{spec\}\} = A / V_\{\\text\{Ni\}\}\$",
     "<var>S<sub>spec</sub> = A / V<sub>Ni</sub></var>"),
    (r"\$S_\{\\text\{spec\}\}\$", "<var>S<sub>spec</sub></var>"),
    (r"\$V_\{\\text\{Ni\}\}\$", "<var>V<sub>Ni</sub></var>"),
    (r"\$t \\propto L\^4\$", "<var>t ∝ L⁴</var>"),
    (r"\$n_N = 0\$", "<var>n<sub>N</sub> = 0</var>"),
    (r"\$n_P = 6 - n_N - n_Y\$", "<var>n<sub>P</sub> = 6 − n<sub>N</sub> − n<sub>Y</sub></var>"),
]


def prep(md):
    for tex, html in EQ.items():
        md = md.replace("$$\n" + tex + "\n$$", f"\n<div class='eq'>{html}</div>\n")
        md = md.replace("$$" + tex + "$$", f"\n<div class='eq'>{html}</div>\n")
    for pat, rep in INLINE:
        md = re.sub(pat, rep, md)
    md = re.sub(r"\$([^$\n]{1,40}?)\$", r"<var>\1</var>", md)   # leftovers
    return md


def embed(name):
    with open(os.path.join(FIGS, name), "rb") as fh:
        return "data:image/png;base64," + base64.b64encode(fh.read()).decode()


def main():
    md = open(SRC, encoding="utf8").read()

    # strip the H1 and the standfirst H3 -- the page furnishes its own masthead
    md = md.split("\n", 1)[1] if md.startswith("# ") else md
    md = re.sub(r"^\s*### A primer on[^\n]*\n", "", md, count=1)

    md = prep(md)
    missing = []
    for i, (fname, anchor, cap, wide) in enumerate(PLACEMENTS, 1):
        a = prep(anchor)
        # the markdown source is hard-wrapped, so anchors span line breaks
        rx = re.compile(r"\s+".join(re.escape(w) for w in a.split()))
        m = rx.search(md)
        if not m:
            missing.append(fname)
            continue
        fig = (f"\n\n<figure class=\"{'wide' if wide else ''}\">"
               f"<img src=\"{embed(fname)}\" alt=\"{cap}\">"
               f"<figcaption><span class=\"fignum\">Figure {i}</span>{cap}"
               f"</figcaption></figure>\n\n")
        md = md[:m.end()] + fig + md[m.end():]
    if missing:
        print("ANCHOR NOT FOUND for:", missing)

    body = markdown.markdown(
        md, extensions=["tables", "attr_list", "md_in_html", "sane_lists"])
    body = body.replace("<table>", "<div class='tw'><table>").replace(
        "</table>", "</table></div>")

    html = TEMPLATE.replace("{{BODY}}", body)
    with open(DST, "w", encoding="utf8") as fh:
        fh.write(html)
    kb = os.path.getsize(DST) / 1024
    print(f"wrote {DST}  ({kb:.0f} KB, {len(PLACEMENTS)-len(missing)}"
          f"/{len(PLACEMENTS)} figures placed)")


TEMPLATE = r"""<title>When the validity check destroys the physics</title>
<style>
:root{
  --paper:#f6f7f5; --plate:#ffffff; --ink:#15181b; --ink2:#4a5057; --ink3:#787f86;
  --rule:#dcdfda; --rule2:#eceee9;
  --ni:#2a78d6; --ysz:#b8501f; --junct:#c0392f;
  --serif: Charter, "Iowan Old Style", Georgia, "Times New Roman", serif;
  --sans: system-ui, -apple-system, "Segoe UI", sans-serif;
  --mono: ui-monospace, "SF Mono", "Cascadia Mono", Consolas, monospace;
}
@media (prefers-color-scheme: dark){
  :root:where(:not([data-theme="light"])){
    --paper:#131518; --plate:#f6f7f5; --ink:#e6e8e6; --ink2:#a8aeb2; --ink3:#7d848a;
    --rule:#2a2e33; --rule2:#20242a; --ni:#5b9ce8; --ysz:#e0763f; --junct:#e8615a;
  }
}
:root[data-theme="dark"]{
  --paper:#131518; --plate:#f6f7f5; --ink:#e6e8e6; --ink2:#a8aeb2; --ink3:#7d848a;
  --rule:#2a2e33; --rule2:#20242a; --ni:#5b9ce8; --ysz:#e0763f; --junct:#e8615a;
}
*{box-sizing:border-box}
body{margin:0;background:var(--paper);color:var(--ink);
  font-family:var(--serif);font-size:17px;line-height:1.62;
  -webkit-font-smoothing:antialiased}
.wrap{max-width:1080px;margin:0 auto;padding:0 28px 120px}
.col{max-width:68ch;margin:0 auto}

/* masthead */
header{padding:76px 0 40px;border-bottom:1px solid var(--rule);margin-bottom:44px}
.eyebrow{font-family:var(--sans);font-size:11px;letter-spacing:.16em;
  text-transform:uppercase;color:var(--ink3);margin:0 0 18px}
h1{font-family:var(--serif);font-weight:600;font-size:clamp(30px,4.6vw,50px);
  line-height:1.08;letter-spacing:-.018em;margin:0 0 18px;text-wrap:balance}
.standfirst{font-size:20px;line-height:1.5;color:var(--ink2);margin:0;
  max-width:60ch;text-wrap:balance}
.swatches{display:flex;gap:0;margin:30px 0 0;height:8px;max-width:280px}
.swatches i{flex:1}

h2{font-family:var(--serif);font-weight:600;font-size:27px;line-height:1.2;
  letter-spacing:-.012em;margin:64px 0 6px;padding-top:22px;
  border-top:1px solid var(--rule);text-wrap:balance}
h3{font-family:var(--serif);font-weight:600;font-size:19.5px;margin:38px 0 4px;
  letter-spacing:-.005em}
h2+p,h3+p{margin-top:10px}
p{margin:0 0 17px}
a{color:var(--ni)}
strong{font-weight:650}
em{font-style:italic}

/* square markers: the subject is voxels */
ul{list-style:none;padding-left:22px;margin:0 0 17px}
ul li{position:relative;margin:0 0 9px}
ul li::before{content:"";position:absolute;left:-18px;top:.62em;width:6px;
  height:6px;background:var(--ni)}
ol{padding-left:24px;margin:0 0 17px}
ol li{margin:0 0 9px}

blockquote{margin:26px 0;padding:16px 22px;border-left:3px solid var(--ni);
  background:var(--rule2);font-size:17px}
blockquote p{margin:0}
blockquote strong{color:var(--ink)}

var{font-family:var(--mono);font-style:normal;font-size:.92em;
  background:var(--rule2);padding:.06em .3em;border-radius:2px}
code{font-family:var(--mono);font-size:.87em;background:var(--rule2);
  padding:.1em .34em;border-radius:2px;color:var(--ysz)}
.eq{font-family:var(--mono);font-size:15px;text-align:center;margin:26px 0;
  padding:18px 14px;background:var(--rule2);border:1px solid var(--rule);
  overflow-x:auto;line-height:1.75}
.eq strong{font-size:16.5px}
.frac{display:inline-flex;flex-direction:column;vertical-align:middle;
  text-align:center;margin:0 .3em}
.frac span:first-child{border-bottom:1px solid currentColor;padding:0 .5em .18em}
.frac span:last-child{padding:.18em .5em 0}

.tw{overflow-x:auto;margin:24px 0}
table{border-collapse:collapse;width:100%;font-family:var(--sans);font-size:13.5px;
  font-variant-numeric:tabular-nums}
th{text-align:left;font-weight:600;font-size:11px;letter-spacing:.07em;
  text-transform:uppercase;color:var(--ink3);padding:9px 13px;
  border-bottom:1.5px solid var(--rule);white-space:nowrap}
td{padding:9px 13px;border-bottom:1px solid var(--rule2);color:var(--ink2)}
td strong{color:var(--ink);font-weight:650}
tbody tr:last-child td{border-bottom:1px solid var(--rule)}

figure{margin:38px 0;padding:0}
figure.wide{max-width:1024px;margin-left:50%;transform:translateX(-50%)}
figure img{display:block;width:100%;height:auto;background:var(--plate);
  border:1px solid var(--rule);border-radius:2px}
figcaption{font-family:var(--sans);font-size:12.5px;line-height:1.55;
  color:var(--ink3);margin-top:11px;max-width:70ch}
.fignum{display:inline-block;font-weight:650;letter-spacing:.06em;
  text-transform:uppercase;font-size:10.5px;color:var(--ni);margin-right:9px}

hr{border:0;border-top:1px solid var(--rule);margin:56px 0}
@media (max-width:900px){
  figure.wide{max-width:100%;margin-left:0;transform:none}
  body{font-size:16px}
  .wrap{padding:0 18px 80px}
}
@media (prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}}
</style>

<div class="wrap">
<header>
  <p class="eyebrow">Ni–YSZ degradation · a primer</p>
  <h1>When the validity check destroys the physics</h1>
  <p class="standfirst">How a simulation of electrode degradation can satisfy
  every test you set it — the right tests, chosen for the right reasons — and
  still move the microstructure in the opposite direction from the physics.</p>
  <div class="swatches">
    <i style="background:var(--ni)"></i>
    <i style="background:var(--ysz)"></i>
    <i style="background:#eceae4"></i>
    <i style="background:var(--junct)"></i>
  </div>
</header>
<div class="col">
{{BODY}}
</div>
</div>
"""

if __name__ == "__main__":
    sys.exit(main())
